changed force_rank filter values to match data
BloomTech-Labs/human-rights-first-police-fe-a pull request #336
Opened 2021-09-02 18:21 UTC by kcjerrell

# Description

The graph on the front page that displays the number of incident reports gathered was blank and showed no data. The values it was using to filter incidents by rank were incorrect. They've been updated to match the values in the data, so the graph can render properly.

![graph before fix](https://res.cloudinary.com/hvvmlo7os/image/upload/v1630606483/blue-watch/graph-before_waf1jm.png)

![graph after fix](https://res.cloudinary.com/hvvmlo7os/image/upload/v1630606481/blue-watch/graph-after_wbzoxb.png)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

Using the pre-existing test suite.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

2021-09-02 23:33 UTC, ahmedseragcodes requested changes
Please see comments / slack thread

https://lambda-students.slack.com/archives/C02C8UXQZPY/p1630625436105200?thread_ts=1630625365.104500&cid=C02C8UXQZPY

2021-09-02 23:33 UTC, ahmedseragcodes commented on src/components/graphs/bargraph/HorizontalBar.js
> +      return x.force_rank === 'Rank 2';
So when I console log out dataList on the HorizontalBar.js component, the object that gets returned shows the properties are actually named in that longer way, so need to stay the same

force_rank: "Rank 4 - Chemical & Electric"

https://lambda-students.slack.com/archives/C02C8UXQZPY/p1630625436105200?thread_ts=1630625365.104500&cid=C02C8UXQZPY

2021-09-03 16:03 UTC, ahmedseragcodes approved these changes
After discussing with Kelly, I now see the most recent objects in the return array include a property that matches his correction, approved

2021-09-03 21:06 UTC, kcjerrell commented
combining this with another PR

2021-09-03 21:06 UTC, closed without merging