Feature/remove blue bar
BloomTech-Labs/human-rights-first-police-fe-a pull request #380
Opened 2021-10-04 16:57 UTC by andrewsbusby

# Description
Removing the blue bar in the middle of the page dividing the map section from the stats section of the page.
Fixes # (issue)
Removed stats folder and files. Removed import in Home.js to prevent any errors rendering the page.

## Type of change
A simple feature removal that wasn't necessary. 

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2021-10-05 15:58 UTC, padawan98 reviewed
Thank you,  Andrew. Those files definitely needed to be erased, since we are no longer using the arrow and the blue bar at the bottom of the home page. Would have liked to see some pictures of what it looks like now :)

2021-10-05 16:37 UTC, pflee1989 commented
Great last step toward a MVP! Congrats for scoring this win for the team.

2021-10-05 16:44 UTC, pflee1989 approved these changes
Great change. Let's go ahead.

2021-10-05 16:44 UTC, pflee1989 commented on src/components/Home/Home.js
>            <>
Let's go ahead.

2021-10-05 17:23 UTC, kcjerrell approved these changes
Approved.

2021-10-05 18:05 UTC, paulstgermain requested changes
I'll need you to record the standard Loom walkthrough for this PR before I can commit to reviewing and merging it. Grab a free Loom account and step us through your work, explaining why you made this change, how you made this change, and using the files changed as a reference!

It doesn't have to be long - 5 minutes or less unless more time is required - but this is an important skill that will strengthen your skills as a developer and the amount of value you will bring to any team you join as well as making you a more capable interviewer!

2021-10-05 19:19 UTC, pflee1989 commented
https://www.loom.com/share/a477f02e685740eb91767737b2218b1a

2021-10-06 14:29 UTC, paulstgermain approved these changes

2021-10-06 14:29 UTC, merged