Ux/map incidents
BloomTech-Labs/human-rights-first-police-fe-a pull request #381
Opened 2021-10-04 19:47 UTC by padawan98

# Description

Changed colors of the drop-down menu "view incident reports" on the home screen to make it more eligible and look more polished.

Co-Authored: Luiza Nacif
Co-Authored: Kelly Jerrell

<img width="1275" alt="uxaestheticchanges" src="https://user-images.githubusercontent.com/46506254/135914191-67ab069b-8de9-4e95-93ef-37be29841465.PNG">

## Type of change

- [x] Aesthetic change

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2021-10-04 21:44 UTC, andrewsbusby approved these changes
It looks really good. I think that the color works much better. You can see the difference much easier not.

2021-10-04 21:44 UTC, kcjerrell approved these changes
I think it looks great, of course!

2021-10-05 18:07 UTC, paulstgermain requested changes
I'll need you to record the standard Loom walkthrough for this PR before I can commit to reviewing and merging it. Grab a free Loom account and step us through your work, explaining why you made this change, how you made this change, and using the files changed as a reference!

It doesn't have to be long - 5 minutes or less unless more time is required - but this is an important skill that will strengthen your skills as a developer and the amount of value you will bring to any team you join as well as making you a more capable interviewer!

2021-10-06 14:42 UTC, paulstgermain approved these changes

2021-10-06 14:43 UTC, merged