Feature/timeline
BloomTech-Labs/human-rights-first-police-fe-a pull request #5
Opened 2020-12-10 20:04 UTC by jstewart8053

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

2020-12-10 20:21 UTC, jlong5795 requested changes
Please update title and description section of the pull request.

2020-12-10 23:35 UTC, anthony2698 approved these changes

2020-12-10 23:39 UTC, anthony2698 approved these changes

2020-12-10 23:40 UTC, jstewart8053 commented
Jason, I fixed title and desc.

2020-12-11 15:21 UTC, jlong5795 approved these changes
Thank you for updating PR description. This helps if we need to look through previous merges.

2020-12-11 15:21 UTC, merged