Feature add map filter
BloomTech-Labs/human-rights-first-police-fe-a pull request #8
Opened 2020-12-11 15:28 UTC by mrockingham

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-12-11 16:43 UTC, jlong5795 requested changes
Let's meet and talk about this context vs wrapper situation.

2020-12-11 16:43 UTC, jlong5795 commented on src/components/Main.js
> +import Store from '../components/Store'
Let's talk about removing this. There is a solution that shouldn't need an additional dependency or component files.

2020-12-11 16:43 UTC, jlong5795 commented on src/components/Store.js
> +import React, { createContext, useState } from 'react';
Same as comment on Main.js

2020-12-11 16:43 UTC, jlong5795 commented on src/components/map/MapSearch.js
> +  const [long, setLong] = useContext(ContextLong);;
I still think we should be using a state wrapper that isn't dependent upon an additional dependency but once we do that we should look at these states and see which of them change together and therefore should just be on one object together.

2020-12-11 16:56 UTC, jstewart8053 approved these changes

2020-12-11 17:00 UTC, jlong5795 commented
Please update PR body description to describe what this PR accomplishes.

2020-12-14 16:27 UTC, jlong5795 commented on src/components/map/MapSearch.js
> +                !incidentsOfInterest ? filterDataList.map((data, index) => {
I feel like we need to simplify this component. Perhaps parts can be extracted to separate components. Let's discuss.

2020-12-14 18:10 UTC, jlong5795 approved these changes

2020-12-14 18:10 UTC, merged